name: ez_bookmarks
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  drift: ^2.16.0
  path: ^1.9.0
  path_provider: ^2.1.2
  sqlite3_flutter_libs: ^0.5.20
  http: ^1.2.1
  html: ^0.15.4
  url_launcher: ^6.2.5
  file_picker: ^8.0.0+1
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  riverpod_generator: ^2.4.0
  riverpod_annotation: ^2.3.5
  image_picker: ^1.0.7
  flutter_launcher_icons: ^0.13.1
  android_intent_plus: ^5.0.1
  webview_flutter: ^4.7.0
  sqlite_viewer: ^1.0.5
  external_path: ^1.0.3
  google_fonts: ^6.2.1
  firebase_analytics: ^10.10.2
  firebase_core: ^2.30.0
  google_mobile_ads: ^5.0.0

  envied: ^0.5.3 # undefined
  flutter_hooks: ^0.20.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  drift_dev: ^2.16.0
  build_runner: ^2.4.9

  envied_generator: ^0.5.3 # undefined
  
  
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/no_image.png



flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/green.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/green.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/green.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/green.png"