// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_MpuD6YzOWE9Y8CuYuaApohqlTPEwEDU',
    appId: '1:168553132288:web:35cde13e344596357103e5',
    messagingSenderId: '168553132288',
    projectId: 'ez-bookmarks-68e0f',
    authDomain: 'ez-bookmarks-68e0f.firebaseapp.com',
    storageBucket: 'ez-bookmarks-68e0f.appspot.com',
    measurementId: 'G-LTY9H3MFWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOlpnuUa-pFHyJ-u-2OlxU6zAp1oj-nNQ',
    appId: '1:168553132288:android:111cb617402211db7103e5',
    messagingSenderId: '168553132288',
    projectId: 'ez-bookmarks-68e0f',
    storageBucket: 'ez-bookmarks-68e0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ3UeE4O_Sbo9CejMzt2Ze9FB6UqKmahk',
    appId: '1:168553132288:ios:2cca8f860074f0437103e5',
    messagingSenderId: '168553132288',
    projectId: 'ez-bookmarks-68e0f',
    storageBucket: 'ez-bookmarks-68e0f.appspot.com',
    iosBundleId: 'com.example.ezBookmarks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ3UeE4O_Sbo9CejMzt2Ze9FB6UqKmahk',
    appId: '1:168553132288:ios:2cca8f860074f0437103e5',
    messagingSenderId: '168553132288',
    projectId: 'ez-bookmarks-68e0f',
    storageBucket: 'ez-bookmarks-68e0f.appspot.com',
    iosBundleId: 'com.example.ezBookmarks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_MpuD6YzOWE9Y8CuYuaApohqlTPEwEDU',
    appId: '1:168553132288:web:6c425703ba4a9e337103e5',
    messagingSenderId: '168553132288',
    projectId: 'ez-bookmarks-68e0f',
    authDomain: 'ez-bookmarks-68e0f.firebaseapp.com',
    storageBucket: 'ez-bookmarks-68e0f.appspot.com',
    measurementId: 'G-Y9CL9YNB60',
  );
}
